
schema: ./src/http/post-sorare_update/sorare/graphql/schema.graphql
documents: ./src/http/post-sorare_update/sorare/graphql/{operations,fragments}/**/*.graphql
extensions:
  codegen:
    generates:
      ./src/http/post-sorare_update/sorare/graphql/sdk.ts:
        plugins:
          - add:
              content: "// @ts-nocheck"
          - typescript
          - typescript-operations
          - typescript-graphql-request